HotelSystem/Controllers/GuestController.cs
using HotelSystem.Data;
using HotelSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace HotelSystem.Controllers
{
    public class GuestController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public GuestController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult GetGuestData()
        {
            var GuestData = _context.Guests.ToList();
            return View(GuestData);
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Guest model)
        {
            if (ModelState.IsValid)
            {
                var parameters = new[]
            {
                new SqlParameter("@Fname", model.Fname),
                new SqlParameter("@Lname",model.Lname),
                new SqlParameter("@Email", model.Email),
                new SqlParameter("@address",model.Address),
                new SqlParameter("@phone_num",model.PhoneNumber)
            };

                // Call stored procedure with the parameters
                _context.Database.ExecuteSqlRaw("EXEC SPCreateGuest @Fname, @Lname, @Email, @address, @phone_num", parameters);

                _context.SaveChanges();

                return RedirectToAction("GetGuestData");
            }
            return View(model);
        }
    }
}

HotelSystem/Controllers/ReservationController.cs
using HotelSystem.Data;
using HotelSystem.Models;
using HotelSystem.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace HotelSystem.Controllers
{
    public class ReservationController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public ReservationController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult RoomReservation()
        {
            var roomReservations = _context.Reservations
            .Include(res => res.Rooms) 
            .Where(res => res.Rooms.Any()) // Only include reservations with rooms
            .Select(res => new RoomReservationViewModel
            {
                RoomId = res.Rooms.First().RoomId,  
                RoomType = res.Rooms.First().Type,   
                RoomStatus = res.Rooms.First().Status,
                ReservationId = res.ResId,
            }).ToList();

            return View(roomReservations);
        }
        [HttpPost]
        public IActionResult Delete(Room model)
        {
            var parameter = new SqlParameter("@id", model.RoomId);

            _context.Database.ExecuteSqlRaw("EXEC DeleteReservationByRoomId @id", parameter);
            _context.SaveChanges();

            return RedirectToAction("GetRoomData","Home");
        }
    }
}

HotelSystem/Controllers/RoomController.cs
using HotelSystem.Data;
using HotelSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace HotelSystem.Controllers
{
    public class RoomController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public RoomController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult GetRoomDataa()
        {
            var RoomData = _context.Rooms.ToList();

            return View(RoomData);
        }
        public IActionResult Update(int id)
        {
            var RoomDetails = _context.Rooms.Find(id);

            return View(RoomDetails);
        }
        [HttpPost]
        public IActionResult Update(Room model)
        {
            var parameters = new[]
            {
                new SqlParameter("@id", model.RoomId),
                new SqlParameter("@Type",model.Type),
                new SqlParameter("@Status", model.Status),
                new SqlParameter("@price",model.Price),

            };

            _context.Database.ExecuteSqlRaw("SpUpdateRoom @id, @Type, @Status, @price", parameters);
            _context.SaveChanges();

            return RedirectToAction("GetRoomDataa");
        }
    }
}

HotelSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HotelSystem</title>
    <link rel="stylesheet" href="css/main_style.css">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/all.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HotelSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand ms-4 text-white fs-5" asp-area="" asp-controller="Home" asp-action="Index">Hotel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto p-2">
                        <li class="nav-item mx-3">
                            <a class="nav-link text-white fs-5" asp-area="" asp-controller="Home" asp-action="GetRoomData">Available Room</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link text-white fs-5" asp-area="" asp-controller="Room" asp-action="GetRoomDataa">All Room</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link text-white fs-5" asp-area="" asp-controller="Guest" asp-action="Add">Guest</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link text-white fs-5" asp-area="" asp-controller="Reservation" asp-action="RoomReservation">Reservation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>